insert into private.permissions(id,permission_key,description,is_sensitive)
values(md5('falcon-permission:courier_settlements.finalize')::uuid,'courier_settlements.finalize','Finalize approved courier settlements',true)
on conflict(permission_key)do nothing;

create or replace function private.courier_settlement_approval_payload(p_settlement_id uuid)
returns jsonb language sql stable security definer set search_path=''
as $$
select jsonb_build_object(
  'organization_id',s.organization_id,'courier_settlement_id',s.id,'courier_id',s.courier_id,
  'settlement_number',s.settlement_no,'period_start',s.period_start,'period_end',s.period_end,
  'expected_settlement_date',s.expected_settlement_date,'actual_settlement_date',s.actual_settlement_date,
  'contractual_cod_minor',s.contractual_cod_minor,'delivery_fees_minor',s.delivery_fees_minor,
  'return_fees_minor',s.return_fees_minor,'approved_deductions_minor',s.approved_deductions_minor,
  'adjustments_minor',s.adjustments_minor,'prior_carry_forward_minor',s.prior_carry_forward_minor,
  'expected_net_settlement_minor',s.expected_net_settlement_minor,'actual_transfer_minor',s.actual_transfer_minor,
  'difference_minor',s.difference_minor,'difference_classification',s.difference_classification,
  'difference_explanation',s.difference_explanation,'evidence_attachment_id',s.evidence_attachment_id,
  'is_off_cycle',s.is_off_cycle,'off_cycle_reason',s.off_cycle_reason,
  'items',(select jsonb_agg(jsonb_build_object(
    'line_type',i.line_type,'shipment_id',i.shipment_id,'shipment_item_id',i.shipment_item_id,
    'return_id',i.return_id,'source_event_key',i.source_event_key,'amount_minor',i.amount_minor,
    'courier_reported_amount_minor',i.courier_reported_amount_minor
  )order by i.source_event_key)from public.courier_settlement_items i where i.courier_settlement_id=s.id and i.is_active)
)from public.courier_settlements s where s.id=p_settlement_id
$$;
revoke all on function private.courier_settlement_approval_payload(uuid)from public,anon,authenticated;

create or replace function private.command_prepare_courier_settlement(
  p_organization_id uuid,p_courier_id uuid,p_settlement_number text,
  p_period_start date,p_period_end date,p_expected_settlement_date date,
  p_actual_settlement_date date,p_actual_transfer_minor bigint,
  p_approved_deductions_minor bigint,p_adjustments_minor bigint,p_prior_carry_forward_minor bigint,
  p_difference_classification text,p_difference_explanation text,p_evidence_attachment_id uuid,
  p_is_off_cycle boolean,p_off_cycle_reason text,p_idempotency_key text,p_request_fingerprint text,
  p_correlation_id uuid default extensions.gen_random_uuid()
)returns jsonb language plpgsql volatile security definer set search_path=''
as $$
declare
  v_claim record;v_settlement_id uuid:=extensions.gen_random_uuid();v_cod bigint;v_delivery bigint;v_returns bigint;
  v_expected bigint;v_difference bigint;v_approval_payload jsonb;v_approval_fingerprint text;v_approval_id uuid;
  v_result jsonb;v_sqlstate text;
  v_payload jsonb:=jsonb_build_object('organization_id',p_organization_id,'courier_id',p_courier_id,'settlement_number',p_settlement_number,'period_start',p_period_start,'period_end',p_period_end,'expected_settlement_date',p_expected_settlement_date,'actual_settlement_date',p_actual_settlement_date,'actual_transfer_minor',p_actual_transfer_minor,'approved_deductions_minor',p_approved_deductions_minor,'adjustments_minor',p_adjustments_minor,'prior_carry_forward_minor',p_prior_carry_forward_minor,'difference_classification',p_difference_classification,'difference_explanation',p_difference_explanation,'evidence_attachment_id',p_evidence_attachment_id,'is_off_cycle',p_is_off_cycle,'off_cycle_reason',p_off_cycle_reason);
begin
  perform private.require_permission(p_organization_id,'courier_settlements.prepare');perform private.assert_request_fingerprint('courier_settlements.prepare',v_payload,p_request_fingerprint,1::smallint);
  if nullif(btrim(p_settlement_number),'')is null or p_period_end<p_period_start or p_actual_transfer_minor<0 or p_approved_deductions_minor<0 or p_actual_settlement_date is null or(p_is_off_cycle and nullif(btrim(p_off_cycle_reason),'')is null)then raise exception using errcode='22023',message='INVALID_COURIER_SETTLEMENT';end if;
  select * into v_claim from private.claim_command(p_organization_id,'courier_settlements.prepare',p_idempotency_key,p_request_fingerprint,1::smallint,p_correlation_id);if v_claim.is_replay then return private.command_replay_response(v_claim.command_status,v_claim.result_reference,v_claim.error_code,v_claim.command_execution_id);end if;
  begin
    perform 1 from public.couriers c where c.organization_id=p_organization_id and c.id=p_courier_id and c.is_active for update;if not found then raise exception using errcode='23503',message='ACTIVE_COURIER_REQUIRED';end if;
    perform 1 from public.shipments s where s.organization_id=p_organization_id and s.courier_id=p_courier_id and s.status in('partially_delivered','delivered','returned') and(s.delivered_at at time zone 'Africa/Cairo')::date between p_period_start and p_period_end order by s.id for update;
    insert into public.courier_settlements(id,organization_id,courier_id,settlement_no,period_start,period_end,expected_settlement_date,status,contractual_cod_minor,delivery_fees_minor,return_fees_minor,approved_deductions_minor,adjustments_minor,prior_carry_forward_minor,expected_net_settlement_minor,is_off_cycle,off_cycle_reason,created_by,updated_by)
    values(v_settlement_id,p_organization_id,p_courier_id,p_settlement_number,p_period_start,p_period_end,p_expected_settlement_date,'draft',0,0,0,p_approved_deductions_minor,p_adjustments_minor,p_prior_carry_forward_minor,-p_approved_deductions_minor+p_adjustments_minor+p_prior_carry_forward_minor,p_is_off_cycle,p_off_cycle_reason,auth.uid(),auth.uid());
    insert into public.courier_settlement_items(organization_id,courier_settlement_id,line_type,shipment_id,source_event_key,amount_minor,courier_reported_amount_minor,description,created_by,updated_by)
    select p_organization_id,v_settlement_id,'contractual_cod_receivable',s.id,'shipment:'||s.id||':contractual_cod',s.expected_cod_minor,s.reported_collected_cod_minor,'Contractual COD receivable',auth.uid(),auth.uid()
    from public.shipments s where s.organization_id=p_organization_id and s.courier_id=p_courier_id and s.status in('partially_delivered','delivered','returned') and s.expected_cod_minor>0 and(s.delivered_at at time zone 'Africa/Cairo')::date between p_period_start and p_period_end and not exists(select 1 from public.courier_settlement_items i where i.organization_id=p_organization_id and i.source_event_key='shipment:'||s.id||':contractual_cod' and i.is_active);
    insert into public.courier_settlement_items(organization_id,courier_settlement_id,line_type,shipment_id,source_event_key,amount_minor,description,created_by,updated_by)
    select p_organization_id,v_settlement_id,'delivery_fee_payable',s.id,'shipment:'||s.id||':delivery_fee',s.courier_delivery_fee_minor,'Contractual delivery fee payable',auth.uid(),auth.uid()
    from public.shipments s where s.organization_id=p_organization_id and s.courier_id=p_courier_id and s.status in('partially_delivered','delivered','returned') and s.courier_delivery_fee_minor>0 and(s.delivered_at at time zone 'Africa/Cairo')::date between p_period_start and p_period_end and not exists(select 1 from public.courier_settlement_items i where i.organization_id=p_organization_id and i.source_event_key='shipment:'||s.id||':delivery_fee' and i.is_active);
    insert into public.courier_settlement_items(organization_id,courier_settlement_id,line_type,shipment_id,return_id,source_event_key,amount_minor,description,created_by,updated_by)
    select p_organization_id,v_settlement_id,'return_fee_payable',s.id,r.id,'return:'||r.id||':return_fee',r.courier_return_fee_minor,'Actual resolved return fee payable',auth.uid(),auth.uid()
    from public.returns r join public.shipments s on s.organization_id=r.organization_id and s.id=r.shipment_id
    where r.organization_id=p_organization_id and s.courier_id=p_courier_id and r.status='resolved' and r.courier_return_fee_minor>0 and(r.inspected_at at time zone 'Africa/Cairo')::date between p_period_start and p_period_end and not exists(select 1 from public.courier_settlement_items i where i.organization_id=p_organization_id and i.source_event_key='return:'||r.id||':return_fee' and i.is_active);
    if p_approved_deductions_minor>0 then insert into public.courier_settlement_items(organization_id,courier_settlement_id,line_type,source_event_key,amount_minor,description,created_by,updated_by)values(p_organization_id,v_settlement_id,'approved_deduction','settlement:'||v_settlement_id||':deduction',p_approved_deductions_minor,'Approved courier deduction',auth.uid(),auth.uid());end if;
    if p_adjustments_minor<>0 then insert into public.courier_settlement_items(organization_id,courier_settlement_id,line_type,source_event_key,amount_minor,description,created_by,updated_by)values(p_organization_id,v_settlement_id,'adjustment','settlement:'||v_settlement_id||':adjustment',p_adjustments_minor,'Approved settlement adjustment',auth.uid(),auth.uid());end if;
    if p_prior_carry_forward_minor<>0 then insert into public.courier_settlement_items(organization_id,courier_settlement_id,line_type,source_event_key,amount_minor,description,created_by,updated_by)values(p_organization_id,v_settlement_id,'prior_carry_forward','settlement:'||v_settlement_id||':carry',p_prior_carry_forward_minor,'Prior approved carry forward',auth.uid(),auth.uid());end if;
    select coalesce(sum(amount_minor)filter(where line_type='contractual_cod_receivable'),0),coalesce(sum(amount_minor)filter(where line_type='delivery_fee_payable'),0),coalesce(sum(amount_minor)filter(where line_type='return_fee_payable'),0)into v_cod,v_delivery,v_returns from public.courier_settlement_items where courier_settlement_id=v_settlement_id and is_active;
    if v_cod=0 and v_delivery=0 and v_returns=0 and p_approved_deductions_minor=0 and p_adjustments_minor=0 and p_prior_carry_forward_minor=0 then raise exception using errcode='23514',message='NO_UNSETTLED_COURIER_EVENTS';end if;
    v_expected:=v_cod-v_delivery-v_returns-p_approved_deductions_minor+p_adjustments_minor+p_prior_carry_forward_minor;v_difference:=p_actual_transfer_minor-v_expected;
    update public.courier_settlements set contractual_cod_minor=v_cod,delivery_fees_minor=v_delivery,return_fees_minor=v_returns,expected_net_settlement_minor=v_expected where id=v_settlement_id;
    v_approval_payload:=private.courier_settlement_approval_payload(v_settlement_id)||jsonb_build_object('actual_settlement_date',p_actual_settlement_date,'actual_transfer_minor',p_actual_transfer_minor,'difference_minor',v_difference,'difference_classification',p_difference_classification,'difference_explanation',p_difference_explanation,'evidence_attachment_id',p_evidence_attachment_id);
    v_approval_fingerprint:=encode(extensions.digest(convert_to(v_approval_payload::text,'UTF8'),'sha256'),'hex');
    v_approval_id:=private.command_submit_approval_request(p_organization_id,'courier_settlement.approve','courier_settlement',v_settlement_id,'courier_settlements.approve','Approve immutable courier reconciliation',v_approval_payload,v_approval_fingerprint,p_actual_transfer_minor,null,statement_timestamp()+interval '14 days');
    if v_difference<>0 and(nullif(btrim(p_difference_classification),'')is null or nullif(btrim(p_difference_explanation),'')is null or p_evidence_attachment_id is null)then raise exception using errcode='23514',message='COURIER_DIFFERENCE_EVIDENCE_REQUIRED';end if;
    update public.courier_settlements set status='prepared',actual_settlement_date=p_actual_settlement_date,actual_transfer_minor=p_actual_transfer_minor,difference_minor=v_difference,difference_classification=p_difference_classification,difference_explanation=p_difference_explanation,evidence_attachment_id=p_evidence_attachment_id,approval_request_id=v_approval_id,version=version+1 where id=v_settlement_id;
    v_result:=private.command_success_response(v_claim.command_execution_id,v_settlement_id,'prepared','courier_settlement.prepared','[]'::jsonb,jsonb_build_object('approval_request_id',v_approval_id,'expected_net_settlement_minor',v_expected,'difference_minor',v_difference));perform private.complete_command_success(v_claim.command_execution_id,v_result);return v_result;
  exception when others then v_sqlstate:=sqlstate;if private.is_retryable_sqlstate(v_sqlstate)then return private.release_retryable_command(v_claim.command_execution_id,v_sqlstate,'courier_settlements.prepare','courier_settlement',null,p_idempotency_key,p_correlation_id);end if;perform private.complete_command_failure(v_claim.command_execution_id,'COURIER_SETTLEMENT_PREPARATION_REJECTED',null);return private.command_replay_response('failed_terminal',null,'COURIER_SETTLEMENT_PREPARATION_REJECTED',v_claim.command_execution_id);end;
end;$$;

create or replace function private.command_approve_courier_settlement(p_organization_id uuid,p_courier_settlement_id uuid,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql volatile security definer set search_path=''
as $$declare v_claim record;v_settlement public.courier_settlements;v_approval public.approval_requests;v_payload jsonb:=jsonb_build_object('organization_id',p_organization_id,'courier_settlement_id',p_courier_settlement_id);v_scope jsonb;v_scope_fp text;v_result jsonb;v_sqlstate text;begin
perform private.require_permission(p_organization_id,'courier_settlements.approve');perform private.assert_request_fingerprint('courier_settlements.approve',v_payload,p_request_fingerprint,1::smallint);select * into v_claim from private.claim_command(p_organization_id,'courier_settlements.approve',p_idempotency_key,p_request_fingerprint,1::smallint,p_correlation_id);if v_claim.is_replay then return private.command_replay_response(v_claim.command_status,v_claim.result_reference,v_claim.error_code,v_claim.command_execution_id);end if;
begin select s.* into strict v_settlement from public.courier_settlements s where s.organization_id=p_organization_id and s.id=p_courier_settlement_id for update;if v_settlement.status<>'prepared'or v_settlement.created_by=auth.uid()then raise exception using errcode='42501',message='COURIER_SETTLEMENT_APPROVAL_SOD_OR_STATE_INVALID';end if;perform 1 from public.courier_settlement_items i where i.courier_settlement_id=v_settlement.id order by i.id for update;
v_scope:=private.courier_settlement_approval_payload(v_settlement.id);v_scope_fp:=encode(extensions.digest(convert_to(v_scope::text,'UTF8'),'sha256'),'hex');select ar.* into strict v_approval from public.approval_requests ar where ar.organization_id=p_organization_id and ar.id=v_settlement.approval_request_id;if v_approval.payload_snapshot<>v_scope or v_approval.subject_fingerprint<>v_scope_fp then raise exception using errcode='55000',message='COURIER_SETTLEMENT_APPROVAL_SCOPE_CHANGED';end if;perform private.consume_approval(p_organization_id,v_approval.id,'courier_settlement.approve','courier_settlement',v_settlement.id,v_scope_fp,v_claim.command_execution_id,v_settlement.actual_transfer_minor);update public.courier_settlements set status='approved',version=version+1 where id=v_settlement.id;v_result:=private.command_success_response(v_claim.command_execution_id,v_settlement.id,'approved','courier_settlement.approved');perform private.complete_command_success(v_claim.command_execution_id,v_result);return v_result;
exception when others then v_sqlstate:=sqlstate;if private.is_retryable_sqlstate(v_sqlstate)then return private.release_retryable_command(v_claim.command_execution_id,v_sqlstate,'courier_settlements.approve','courier_settlement',p_courier_settlement_id,p_idempotency_key,p_correlation_id);end if;perform private.complete_command_failure(v_claim.command_execution_id,'COURIER_SETTLEMENT_APPROVAL_REJECTED',null);return private.command_replay_response('failed_terminal',null,'COURIER_SETTLEMENT_APPROVAL_REJECTED',v_claim.command_execution_id);end;end$$;

create or replace function private.command_finalize_courier_settlement(p_organization_id uuid,p_courier_settlement_id uuid,p_wallet_id uuid,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql volatile security definer set search_path=''
as $$declare v_claim record;v_settlement public.courier_settlements;v_wallet public.wallets;v_fees bigint;v_difference bigint;v_lines jsonb:='[]'::jsonb;v_journal uuid;v_result jsonb;v_sqlstate text;v_payload jsonb:=jsonb_build_object('organization_id',p_organization_id,'courier_settlement_id',p_courier_settlement_id,'wallet_id',p_wallet_id);begin
perform private.require_permission(p_organization_id,'courier_settlements.finalize');perform private.assert_request_fingerprint('courier_settlements.finalize',v_payload,p_request_fingerprint,1::smallint);select * into v_claim from private.claim_command(p_organization_id,'courier_settlements.finalize',p_idempotency_key,p_request_fingerprint,1::smallint,p_correlation_id);if v_claim.is_replay then return private.command_replay_response(v_claim.command_status,v_claim.result_reference,v_claim.error_code,v_claim.command_execution_id);end if;
begin select s.* into strict v_settlement from public.courier_settlements s where s.organization_id=p_organization_id and s.id=p_courier_settlement_id for update;select w.* into strict v_wallet from public.wallets w where w.organization_id=p_organization_id and w.id=p_wallet_id and w.is_active for update;if v_settlement.status<>'approved'or(select resolved_by from public.approval_requests where id=v_settlement.approval_request_id)=auth.uid()then raise exception using errcode='42501',message='COURIER_SETTLEMENT_FINALIZE_SOD_OR_STATE_INVALID';end if;v_fees:=v_settlement.delivery_fees_minor+v_settlement.return_fees_minor+v_settlement.approved_deductions_minor;v_difference:=v_settlement.difference_minor;
if v_settlement.actual_transfer_minor>0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','wallet_'||lower(regexp_replace(v_wallet.code,'[^a-zA-Z0-9]+','_','g')),'debit_minor',v_settlement.actual_transfer_minor::text,'credit_minor','0','wallet_id',v_wallet.id,'subledger_type','courier_settlement','subledger_id',v_settlement.id));end if;
if v_fees>0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','courier_payables','debit_minor',v_fees::text,'credit_minor','0','subledger_type','courier_settlement','subledger_id',v_settlement.id));end if;
if v_settlement.adjustments_minor+v_settlement.prior_carry_forward_minor<0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','courier_settlement_variance','debit_minor',(-(v_settlement.adjustments_minor+v_settlement.prior_carry_forward_minor))::text,'credit_minor','0','subledger_type','courier_adjustment','subledger_id',v_settlement.id));elsif v_settlement.adjustments_minor+v_settlement.prior_carry_forward_minor>0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','courier_settlement_variance','debit_minor','0','credit_minor',(v_settlement.adjustments_minor+v_settlement.prior_carry_forward_minor)::text,'subledger_type','courier_adjustment','subledger_id',v_settlement.id));end if;
if v_difference<0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','courier_settlement_variance','debit_minor',(-v_difference)::text,'credit_minor','0','subledger_type','courier_difference','subledger_id',v_settlement.id));elsif v_difference>0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','courier_settlement_variance','debit_minor','0','credit_minor',v_difference::text,'subledger_type','courier_difference','subledger_id',v_settlement.id));end if;
if v_settlement.contractual_cod_minor>0 then v_lines:=v_lines||jsonb_build_array(jsonb_build_object('account_role','courier_receivables','debit_minor','0','credit_minor',v_settlement.contractual_cod_minor::text,'subledger_type','courier_settlement','subledger_id',v_settlement.id));end if;
v_journal:=private.post_journal_entry(p_organization_id=>p_organization_id,p_source_type=>'courier_settlement',p_source_id=>v_settlement.id,p_posting_purpose=>'finalization',p_description=>'Finalize approved courier settlement',p_lines=>v_lines,p_idempotency_key=>p_idempotency_key,p_request_hash=>p_request_fingerprint,p_correlation_id=>p_correlation_id,p_approval_request_id=>v_settlement.approval_request_id,p_command_type=>'courier_settlements.finalize',p_command_execution_id=>v_claim.command_execution_id,p_require_manual_permission=>false);
update public.courier_settlements set status='posted',wallet_id=p_wallet_id,journal_entry_id=v_journal,posted_at=statement_timestamp(),version=version+1 where id=v_settlement.id;update public.shipments s set settlement_status='settled',version=version+1 where s.organization_id=p_organization_id and exists(select 1 from public.courier_settlement_items i where i.courier_settlement_id=v_settlement.id and i.shipment_id=s.id and i.is_active);v_result:=private.command_success_response(v_claim.command_execution_id,v_settlement.id,'posted','courier_settlement.finalized',jsonb_build_array(v_journal));perform private.complete_command_success(v_claim.command_execution_id,v_result);return v_result;
exception when others then v_sqlstate:=sqlstate;if private.is_retryable_sqlstate(v_sqlstate)then return private.release_retryable_command(v_claim.command_execution_id,v_sqlstate,'courier_settlements.finalize','courier_settlement',p_courier_settlement_id,p_idempotency_key,p_correlation_id);end if;perform private.complete_command_failure(v_claim.command_execution_id,'COURIER_SETTLEMENT_FINALIZATION_REJECTED',null);return private.command_replay_response('failed_terminal',null,'COURIER_SETTLEMENT_FINALIZATION_REJECTED',v_claim.command_execution_id);end;end$$;

create or replace function api.prepare_courier_settlement(p_organization_id uuid,p_courier_id uuid,p_settlement_number text,p_period_start date,p_period_end date,p_expected_settlement_date date,p_actual_settlement_date date,p_actual_transfer_minor bigint,p_approved_deductions_minor bigint,p_adjustments_minor bigint,p_prior_carry_forward_minor bigint,p_difference_classification text,p_difference_explanation text,p_evidence_attachment_id uuid,p_is_off_cycle boolean,p_off_cycle_reason text,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language sql volatile security invoker set search_path=''as $$select private.command_prepare_courier_settlement(p_organization_id,p_courier_id,p_settlement_number,p_period_start,p_period_end,p_expected_settlement_date,p_actual_settlement_date,p_actual_transfer_minor,p_approved_deductions_minor,p_adjustments_minor,p_prior_carry_forward_minor,p_difference_classification,p_difference_explanation,p_evidence_attachment_id,p_is_off_cycle,p_off_cycle_reason,p_idempotency_key,p_request_fingerprint,p_correlation_id)$$;
create or replace function api.approve_courier_settlement(p_organization_id uuid,p_courier_settlement_id uuid,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language sql volatile security invoker set search_path=''as $$select private.command_approve_courier_settlement(p_organization_id,p_courier_settlement_id,p_idempotency_key,p_request_fingerprint,p_correlation_id)$$;
create or replace function api.finalize_courier_settlement(p_organization_id uuid,p_courier_settlement_id uuid,p_wallet_id uuid,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language sql volatile security invoker set search_path=''as $$select private.command_finalize_courier_settlement(p_organization_id,p_courier_settlement_id,p_wallet_id,p_idempotency_key,p_request_fingerprint,p_correlation_id)$$;

revoke all on function private.command_prepare_courier_settlement(uuid,uuid,text,date,date,date,date,bigint,bigint,bigint,bigint,text,text,uuid,boolean,text,text,text,uuid)from public,anon,authenticated;revoke all on function private.command_approve_courier_settlement(uuid,uuid,text,text,uuid)from public,anon,authenticated;revoke all on function private.command_finalize_courier_settlement(uuid,uuid,uuid,text,text,uuid)from public,anon,authenticated;
grant execute on function private.command_prepare_courier_settlement(uuid,uuid,text,date,date,date,date,bigint,bigint,bigint,bigint,text,text,uuid,boolean,text,text,text,uuid)to authenticated;grant execute on function private.command_approve_courier_settlement(uuid,uuid,text,text,uuid)to authenticated;grant execute on function private.command_finalize_courier_settlement(uuid,uuid,uuid,text,text,uuid)to authenticated;
revoke all on function api.prepare_courier_settlement(uuid,uuid,text,date,date,date,date,bigint,bigint,bigint,bigint,text,text,uuid,boolean,text,text,text,uuid)from public,anon,authenticated;revoke all on function api.approve_courier_settlement(uuid,uuid,text,text,uuid)from public,anon,authenticated;revoke all on function api.finalize_courier_settlement(uuid,uuid,uuid,text,text,uuid)from public,anon,authenticated;
grant execute on function api.prepare_courier_settlement(uuid,uuid,text,date,date,date,date,bigint,bigint,bigint,bigint,text,text,uuid,boolean,text,text,text,uuid)to authenticated;grant execute on function api.approve_courier_settlement(uuid,uuid,text,text,uuid)to authenticated;grant execute on function api.finalize_courier_settlement(uuid,uuid,uuid,text,text,uuid)to authenticated;

create or replace view public.courier_receivable_summary with(security_invoker=true)as
select s.organization_id,s.courier_id,sum(s.expected_cod_minor)::bigint as contractual_cod_minor,coalesce(sum(s.reported_collected_cod_minor),0)::bigint as courier_reported_cod_minor,(sum(s.courier_delivery_fee_minor)+coalesce(sum(rf.return_fees_minor),0))::bigint as accrued_courier_fees_minor,count(*)filter(where s.settlement_status<>'settled')::bigint as unsettled_shipments
from public.shipments s left join lateral(select sum(r.courier_return_fee_minor)::bigint as return_fees_minor from public.returns r where r.organization_id=s.organization_id and r.shipment_id=s.id and r.status='resolved')rf on true
where s.status in('partially_delivered','delivered','returned')group by s.organization_id,s.courier_id;

do $repair$
declare d text;f text;
begin
select pg_get_functiondef('private.command_record_order_return(uuid,uuid,text,jsonb,text,uuid,integer,text,text,uuid)'::regprocedure)into d;
f:=replace(d,'update public.shipments set status=case when not exists','update public.shipments set settlement_status=''unsettled'',status=case when not exists');
if f=d then raise exception 'RETURN_SETTLEMENT_STATUS_REPAIR_NOT_APPLIED';end if;execute f;
end;$repair$;
revoke all on function private.command_record_order_return(uuid,uuid,text,jsonb,text,uuid,integer,text,text,uuid)from public,anon,authenticated;
grant execute on function private.command_record_order_return(uuid,uuid,text,jsonb,text,uuid,integer,text,text,uuid)to authenticated;
