insert into private.permissions(id,permission_key,description,is_sensitive)
select md5('falcon-permission:'||k)::uuid,k,d,true from(values
('partners.capital.record','Record partner capital contributions'),
('partners.loan.record','Record partner-to-Falcon loans'))p(k,d) on conflict(permission_key)do nothing;

create or replace function private.command_record_partner_capital(p_organization_id uuid,p_partner_id uuid,p_wallet_id uuid,p_amount_minor bigint,p_reason text,p_evidence_attachment_id uuid,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql volatile security definer set search_path=''
as $$declare v_claim record;v_wallet public.wallets;v_id uuid:=extensions.gen_random_uuid();v_journal uuid;v_result jsonb;v_sqlstate text;v_payload jsonb:=jsonb_build_object('organization_id',p_organization_id,'partner_id',p_partner_id,'wallet_id',p_wallet_id,'amount_minor',p_amount_minor,'reason',p_reason,'evidence_attachment_id',p_evidence_attachment_id);begin
perform private.require_permission(p_organization_id,'partners.capital.record');perform private.assert_request_fingerprint('partners.capital.record',v_payload,p_request_fingerprint,1::smallint);if p_amount_minor<=0 or nullif(btrim(p_reason),'')is null then raise exception using errcode='22023',message='INVALID_CAPITAL_CONTRIBUTION';end if;select * into v_claim from private.claim_command(p_organization_id,'partners.capital.record',p_idempotency_key,p_request_fingerprint,1::smallint,p_correlation_id);if v_claim.is_replay then return private.command_replay_response(v_claim.command_status,v_claim.result_reference,v_claim.error_code,v_claim.command_execution_id);end if;
begin perform 1 from public.partners where organization_id=p_organization_id and id=p_partner_id and is_active for update;select w.* into strict v_wallet from public.wallets w where w.organization_id=p_organization_id and w.id=p_wallet_id and w.is_active for update;
v_journal:=private.post_journal_entry(p_organization_id=>p_organization_id,p_source_type=>'partner_capital',p_source_id=>v_id,p_posting_purpose=>'contribution',p_description=>'Partner capital contribution',p_lines=>jsonb_build_array(jsonb_build_object('account_role','wallet_'||lower(regexp_replace(v_wallet.code,'[^a-zA-Z0-9]+','_','g')),'debit_minor',p_amount_minor::text,'credit_minor','0','wallet_id',v_wallet.id,'partner_id',p_partner_id,'subledger_type','partner_capital','subledger_id',v_id),jsonb_build_object('account_role','partner_capital','debit_minor','0','credit_minor',p_amount_minor::text,'partner_id',p_partner_id,'subledger_type','partner_capital','subledger_id',v_id)),p_idempotency_key=>p_idempotency_key,p_request_hash=>p_request_fingerprint,p_correlation_id=>p_correlation_id,p_command_type=>'partners.capital.record',p_command_execution_id=>v_claim.command_execution_id,p_require_manual_permission=>false);
insert into public.partner_capital_transactions(id,organization_id,partner_id,transaction_type,amount_minor,accounting_date,wallet_id,reason,evidence_attachment_id,journal_entry_id,created_by,updated_by)values(v_id,p_organization_id,p_partner_id,'capital_contribution',p_amount_minor,private.cairo_accounting_date(),v_wallet.id,p_reason,p_evidence_attachment_id,v_journal,auth.uid(),auth.uid());v_result:=private.command_success_response(v_claim.command_execution_id,v_id,'posted','partner.capital_recorded',jsonb_build_array(v_journal));perform private.complete_command_success(v_claim.command_execution_id,v_result);return v_result;
exception when others then v_sqlstate:=sqlstate;if private.is_retryable_sqlstate(v_sqlstate)then return private.release_retryable_command(v_claim.command_execution_id,v_sqlstate,'partners.capital.record','partner',p_partner_id,p_idempotency_key,p_correlation_id);end if;perform private.complete_command_failure(v_claim.command_execution_id,'PARTNER_CAPITAL_REJECTED',null);return private.command_replay_response('failed_terminal',null,'PARTNER_CAPITAL_REJECTED',v_claim.command_execution_id);end;end$$;

create or replace function private.command_record_partner_loan(p_organization_id uuid,p_partner_id uuid,p_wallet_id uuid,p_loan_number text,p_principal_minor bigint,p_due_date date,p_terms_snapshot jsonb,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language plpgsql volatile security definer set search_path=''
as $$declare v_claim record;v_wallet public.wallets;v_id uuid:=extensions.gen_random_uuid();v_journal uuid;v_result jsonb;v_sqlstate text;v_payload jsonb:=jsonb_build_object('organization_id',p_organization_id,'partner_id',p_partner_id,'wallet_id',p_wallet_id,'loan_number',p_loan_number,'principal_minor',p_principal_minor,'due_date',p_due_date,'terms_snapshot',p_terms_snapshot);begin
perform private.require_permission(p_organization_id,'partners.loan.record');perform private.assert_request_fingerprint('partners.loan.record',v_payload,p_request_fingerprint,1::smallint);if p_principal_minor<=0 or jsonb_typeof(p_terms_snapshot)<>'object'then raise exception using errcode='22023',message='INVALID_PARTNER_LOAN';end if;select * into v_claim from private.claim_command(p_organization_id,'partners.loan.record',p_idempotency_key,p_request_fingerprint,1::smallint,p_correlation_id);if v_claim.is_replay then return private.command_replay_response(v_claim.command_status,v_claim.result_reference,v_claim.error_code,v_claim.command_execution_id);end if;
begin perform 1 from public.partners where organization_id=p_organization_id and id=p_partner_id and is_active for update;select w.* into strict v_wallet from public.wallets w where w.organization_id=p_organization_id and w.id=p_wallet_id and w.is_active for update;
v_journal:=private.post_journal_entry(p_organization_id=>p_organization_id,p_source_type=>'partner_loan',p_source_id=>v_id,p_posting_purpose=>'funding',p_description=>'Partner loan funding',p_lines=>jsonb_build_array(jsonb_build_object('account_role','wallet_'||lower(regexp_replace(v_wallet.code,'[^a-zA-Z0-9]+','_','g')),'debit_minor',p_principal_minor::text,'credit_minor','0','wallet_id',v_wallet.id,'partner_id',p_partner_id,'subledger_type','partner_loan','subledger_id',v_id),jsonb_build_object('account_role','partner_loans_payable','debit_minor','0','credit_minor',p_principal_minor::text,'partner_id',p_partner_id,'subledger_type','partner_loan','subledger_id',v_id)),p_idempotency_key=>p_idempotency_key,p_request_hash=>p_request_fingerprint,p_correlation_id=>p_correlation_id,p_command_type=>'partners.loan.record',p_command_execution_id=>v_claim.command_execution_id,p_require_manual_permission=>false);
insert into public.partner_loans(id,organization_id,partner_id,loan_no,direction,principal_minor,start_date,due_date,status,terms_snapshot,journal_entry_id,created_by,updated_by)values(v_id,p_organization_id,p_partner_id,p_loan_number,'partner_to_falcon',p_principal_minor,private.cairo_accounting_date(),p_due_date,'active',p_terms_snapshot,v_journal,auth.uid(),auth.uid());v_result:=private.command_success_response(v_claim.command_execution_id,v_id,'active','partner.loan_recorded',jsonb_build_array(v_journal));perform private.complete_command_success(v_claim.command_execution_id,v_result);return v_result;
exception when others then v_sqlstate:=sqlstate;if private.is_retryable_sqlstate(v_sqlstate)then return private.release_retryable_command(v_claim.command_execution_id,v_sqlstate,'partners.loan.record','partner',p_partner_id,p_idempotency_key,p_correlation_id);end if;perform private.complete_command_failure(v_claim.command_execution_id,'PARTNER_LOAN_REJECTED',null);return private.command_replay_response('failed_terminal',null,'PARTNER_LOAN_REJECTED',v_claim.command_execution_id);end;end$$;

create or replace function api.record_partner_capital(p_organization_id uuid,p_partner_id uuid,p_wallet_id uuid,p_amount_minor bigint,p_reason text,p_evidence_attachment_id uuid,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language sql volatile security invoker set search_path=''as $$select private.command_record_partner_capital(p_organization_id,p_partner_id,p_wallet_id,p_amount_minor,p_reason,p_evidence_attachment_id,p_idempotency_key,p_request_fingerprint,p_correlation_id)$$;
create or replace function api.record_partner_loan(p_organization_id uuid,p_partner_id uuid,p_wallet_id uuid,p_loan_number text,p_principal_minor bigint,p_due_date date,p_terms_snapshot jsonb,p_idempotency_key text,p_request_fingerprint text,p_correlation_id uuid default extensions.gen_random_uuid())returns jsonb language sql volatile security invoker set search_path=''as $$select private.command_record_partner_loan(p_organization_id,p_partner_id,p_wallet_id,p_loan_number,p_principal_minor,p_due_date,p_terms_snapshot,p_idempotency_key,p_request_fingerprint,p_correlation_id)$$;
revoke all on function private.command_record_partner_capital(uuid,uuid,uuid,bigint,text,uuid,text,text,uuid)from public,anon,authenticated;revoke all on function private.command_record_partner_loan(uuid,uuid,uuid,text,bigint,date,jsonb,text,text,uuid)from public,anon,authenticated;grant execute on function private.command_record_partner_capital(uuid,uuid,uuid,bigint,text,uuid,text,text,uuid)to authenticated;grant execute on function private.command_record_partner_loan(uuid,uuid,uuid,text,bigint,date,jsonb,text,text,uuid)to authenticated;
revoke all on function api.record_partner_capital(uuid,uuid,uuid,bigint,text,uuid,text,text,uuid)from public,anon,authenticated;revoke all on function api.record_partner_loan(uuid,uuid,uuid,text,bigint,date,jsonb,text,text,uuid)from public,anon,authenticated;grant execute on function api.record_partner_capital(uuid,uuid,uuid,bigint,text,uuid,text,text,uuid)to authenticated;grant execute on function api.record_partner_loan(uuid,uuid,uuid,text,bigint,date,jsonb,text,text,uuid)to authenticated;
